# .github/workflows/chromatic.yml

# name of our action
name: 'Chromatic'
# the event that will trigger the action
on: push

# what the action will do
jobs:
  test:
    # the operating system it will run on
    runs-on: ubuntu-latest
    # the list of steps that the action will go through
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn

      - name: Install storybook dependencies
        run: yarn
        working-directory: storybook

      - name: 🤞 Run CSS Lint 🧪
        run: |
          yarn css-lint:stories

      - name: 🤞 Run Lint 🧪
        run: |
          yarn lint:stories

      - name: Publish to Chromatic
        uses: chromaui/action@v1
        # options required to the GitHub chromatic action
        with:
          workingDir: storybook
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
